export const SECURITY_QUESTIONS = [
  "What was the name of your first pet?",
  "What city were you born in?",
  "What was your mother's maiden name?",
  "What was the name of your elementary school?",
  "What was your childhood nickname?",
  "What was the make of your first car?",
  "What was your favorite food as a child?",
  "What was the name of your best friend in high school?",
  "What street did you grow up on?",
  "What was your favorite subject in school?",
  "What was the name of your first teacher?",
  "What was your first job?",
  "What is your favorite movie?",
  "What was the name of your first crush?",
  "What is your favorite book?",
  "What was your favorite sport in school?",
  "What is your mother's middle name?",
  "What is your father's middle name?",
  "What was the name of your first boss?",
  "What is your favorite color?",
  "What was your favorite vacation destination?",
  "What is your favorite restaurant?",
  "What was the model of your first computer?",
  "What is your favorite song?",
  "What was your high school mascot?",
];

